- addons/headless/XEH_postInit.sqf
- addons/headless/XEH_preInit.sqf
- addons/headless/config.cpp
- addons/headless/functions/fnc_rebalance.sqf
- addons/sitting/XEH_clientInit.sqf
- addons/viewrestriction/XEH_clientInit.sqf
Ref https://github.com/acemod/ACE3/pull/3815
> Update to new CBA event system

- .editorconfig
- .gitattributes
Explanation in https://github.com/acemod/ACE3/pull/3840
> Set LF as default line ending

- addons/sitting/functions/fnc_canSit.sqf
- addons/sitting/functions/fnc_sit.sqf
- addons/sitting/functions/fnc_stand.sqf
Copy of https://github.com/acemod/ACE3/pull/3947
> Fix ability to carry a chair someone is sitting on

- .travis.yml
- tools/config_style_checker.py
- tools/deploy.py
- tools/make.cfg
- tools/make.py
- tools/setup.py
- tools/sqf_validator.py
- tools/stringtablediag.py
- tools/stringtableduplicates.py
> Add translation deployment and update all tools

- addons/main/CfgSettings.hpp
- addons/main/config.cpp
- addons/main/script_mod.hpp
- Title
- ACEX now requires ACE3 3.6.0
> Add CfgSettings CBA versioning requirement for ACE3

- .gitignore
- addons/headless/stringtable.xml
- addons/viewrestriction/stringtable.xml
> Polish translation

- addons/viewrestriction/stringtable.xml
Add the german entries to the stringtable.xml for the viewrestriction
> German string for viewrestrictions

- addons/headless/functions/fnc_handleConnectHC.sqf
- addons/headless/functions/fnc_handleDisconnect.sqf
- addons/headless/functions/fnc_moduleInit.sqf
- addons/headless/functions/fnc_transferGroups.sqf
- addons/main/script_macros.hpp
- addons/sitting/functions/fnc_moduleInit.sqf
- addons/viewrestriction/XEH_clientInit.sqf
- addons/viewrestriction/functions/fnc_moduleInit.sqf
Companion to https://github.com/acemod/ACE3/pull/4282
> Update to new CBA logging macros

- addons/headless/functions/fnc_endMissionNoPlayers.sqf
- addons/killtracker/XEH_postInit.sqf
> Fix 2 more ace/cba log macros

- addons/sitting/config.cpp
> ACE_sitting inherit version from ace_common

- addons/headless/stringtable.xml
- addons/sitting/stringtable.xml
- addons/viewrestriction/stringtable.xml
Japanese translation for v3.1.1
> Jpn translation v311

- addons/viewrestriction/stringtable.xml
- expand Hungarian translations in  viewrestrictions
> Add Hungarian translations 

- addons/headless/CfgEden.hpp
- addons/headless/config.cpp
- addons/headless/stringtable.xml
- Add headless blacklist as an Eden attribute checkbox
- Only adds it to groups and vehicles
> Add headless blacklist Eden attribute

- addons/sitting/stringtable.xml
- Describe what this pull request will do
- Each change in a separate line
- Respect the [Development Guidelines](http://ace3mod.com/wiki/development/)
> Korean Translation - Sitting

- addons/viewrestriction/stringtable.xml
- Describe what this pull request will do
- Each change in a separate line
- Respect the [Development Guidelines](http://ace3mod.com/wiki/development/)
> Korean Translation - View Restriction

- addons/headless/XEH_preInit.sqf
- addons/main/XEH_preInit.sqf
- addons/sitting/XEH_preInit.sqf
- addons/viewrestriction/XEH_preInit.sqf
- extras/blank/XEH_preInit.sqf
- Makes use of https://github.com/acemod/ACE3/pull/4699
> Use dev macro to quickly recompile functions

- addons/main/script_mod.hpp
- Title
Required by `PREP` development macros (#58).
> Require ACE3 v3.9.0

- addons/main/script_mod.hpp
- addons/main/script_version.hpp
- tools/make.py
- Title
- Split version to separate file
Just mimics latest ACE3.
> Update make.py to 0.8

- .github_changelog_generator
> Add GitHub Changelog Generator configuration file

- addons/headless/stringtable.xml
- addons/sitting/stringtable.xml
- addons/viewrestriction/stringtable.xml
- addons/volume/stringtable.xml
- add French strings in the tables
> French localization

- addons/headless/stringtable.xml
- addons/sitting/stringtable.xml
- addons/viewrestriction/stringtable.xml
- addons/volume/stringtable.xml
I translate all ACEX strings content into Chinese.
> Add Chinese Localization into ACEX

- addons/headless/stringtable.xml
- addons/viewrestriction/stringtable.xml
- addons/volume/stringtable.xml
Added:
-volume
-viewrestriction
-headless
> Italian Translation Update

- addons/sitting/functions/fnc_sit.sqf
- addons/sitting/functions/fnc_stand.sqf
- Public listenable events that could help fixing the Enhanced Movement et al floating bug.
> ace_satDown and ace_stoodUp eventhandlers for sitting

- addons/headless/XEH_preInit.sqf
- addons/headless/functions/fnc_handleSpawn.sqf
- addons/headless/functions/fnc_transferGroups.sqf
- addons/headless/script_component.hpp
> Patch UAV problem #81

- addons/headless/functions/fnc_handleConnectHC.sqf
- Not trigger a rebalance if AI distribution is disabled and a HC connects
> Rebalance would be triggered if AI distribution is disabled at HC connect

- addons/headless/functions/fnc_handleConnectHC.sqf
- addons/headless/functions/fnc_handleDisconnect.sqf
> Fix headless exit comments

- addons/fortify/CfgVehicles.hpp
- addons/fortify/functions/fnc_parseSide.sqf
- addons/fortify/functions/fnc_registerObjects.sqf
- addons/fortify/functions/fnc_setupModule.sqf
> Allow civilian side to use fortify

- addons/headless/ACE_Settings.hpp
ref https://github.com/acemod/ACE3/pull/5920
> Add slider settings

- addons/fortify/stringtable.xml
> Update Chinese Language

- addons/fortify/XEH_postInit.sqf
- addons/fortify/functions/fnc_deployConfirm.sqf
> Fortify - Add events when creating / deleting objects

- addons/fortify/CfgVehicles.hpp
- addons/fortify/XEH_PREP.hpp
- addons/fortify/XEH_preInit.sqf
- addons/fortify/functions/fnc_buildLocationModule.sqf
- addons/fortify/functions/fnc_canFortify.sqf
- addons/fortify/stringtable.xml
> Fortify - Add module to limit build locations

- addons/fortify/stringtable.xml
- addons/viewrestriction/stringtable.xml
> Chinese update

- addons/fortify/XEH_postInit.sqf
- addons/fortify/stringtable.xml
- Fix budget hint showing for all sides with tool setting
- Improve hint setting description
> Fortify - Fix budget hint showing for all sides with tool setting

- addons/viewrestriction/functions/fnc_canChangeCamera.sqf
- replace `ace_common_fnc_isFeatureCameraActive` with `CBA_fnc_getActiveFeatureCamera`.
ref CBATeam/CBA_A3#982
> View Restriction - Replace deprecated function call

- addons/headless/CfgEden.hpp
default value now matches checkbox type
> Headless - Fix 3den default value

- .github/ISSUE_TEMPLATE.md
Same as https://github.com/acemod/ACE3/pull/6695 but for ACEX.
> Replace placed modules by additional information in the issue template

- addons/field_rations/stringtable.xml
- as title. support to the new strings.
> Update Japanese translations

- addons/field_rations/XEH_postInit.sqf
> Field Rations - Decrease refill action distance

- addons/field_rations/initSettings.sqf
- Allow for longer and "realistic" food and water values for RP and MilSim
> Increased survival time without for food and water

- addons/field_rations/stringtable.xml
- addons/fortify/stringtable.xml
- addons/headless/stringtable.xml
My first ever upload(github) so i hope everything is right. Might be few typos.
- Describe what this pull request will do
- Each change in a separate line
- Respect the [Development Guidelines](http://ace3mod.com/wiki/development/)
> Polish translation of Field Rations, Fortify and few Headless.

- addons/volume/script_component.hpp
> Enable compile cache for acex_volume

- addons/field_rations/Cfg3DEN.hpp
- addons/field_rations/config.cpp
- addons/field_rations/stringtable.xml
> Field Rations - Add water supply 3DEN attribute

- addons/field_rations/CfgVehicles.hpp
- addons/field_rations/XEH_preInit.sqf
- addons/field_rations/XEH_preStart.sqf
- Add water source P3Ds for vehicles that we already know are sources.
> Field Rations - Add P3Ds From Config

- addons/field_rations/stringtable.xml
- addons/headless/stringtable.xml
> Update Japanese translation

- addons/sitting/functions/fnc_sit.sqf
- Title, the check always failed
> Add missing param to seat distance check

- addons/viewrestriction/README.md
> Fixed link-formatting in Readme

- addons/fortify/functions/fnc_canFortify.sqf
> Fix Fortify cost equals budget

- addons/fortify/functions/fnc_updateBudget.sqf
- title
Ref https://github.com/acemod/ACEX/issues/185
> Fix ability to get negative budget

- addons/field_rations/stringtable.xml
- addons/fortify/stringtable.xml
- addons/headless/stringtable.xml
- addons/viewrestriction/stringtable.xml
- addons/volume/stringtable.xml
- Fix a completes russian translations in files:
addons/field_rations/stringtable.xml
addons/fortify/stringtable.xml
addons/headless/stringtable.xml
addons/viewrestriction/stringtable.xml
addons/volume/stringtable.xml
> Russian translation fixes and update

- addons/field_rations/stringtable.xml
fix some wrong translate,and add missing string
- Describe what this pull request will do
- Each change in a separate line
- Respect the [Development Guidelines](http://ace3mod.com/wiki/development/)
> fix and update chinese translate

- addons/headless/stringtable.xml
> Update missing chinese string

- addons/intelitems/stringtable.xml
> Update tchinese string

- addons/field_rations/stringtable.xml
- addons/intelitems/stringtable.xml
> update tch string on field_rations

- addons/intelitems/XEH_PREP.hpp
- addons/intelitems/functions/fnc_addIntel.sqf
- addons/intelitems/functions/fnc_handleMagIndex.sqf
- addons/intelitems/stringtable.xml
- Add public `addIntel` function to allow users to easily add an intel item to a unit with data
> Intel Items - Add function to add item to unit with data

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
> Tools - Add Release Drafter

- addons/field_rations/functions/fnc_addWaterSourceInteractions.sqf
- Fix interaction helper position for moving objects such as water trucks by attaching it to the object
> Field Rations - Fix interaction position for moving objects

- tools/make.py
- Make `make.py` compatible with latest Mikero Tools updates
> Tools - Removed deprecated Mikero tools arguments from make.py

- .github/workflows/arma.yml
- Title
- Switch https://github.com/arma-actions/bom-check to `v1`
https://github.com/arma-actions/bom-check/issues/1 was fixed.
> Tools - Enable CI BOM Check

- addons/killtracker/README.md
- addons/killtracker/XEH_postInit.sqf
- title, Close #226 
- Change "Acex" to "ACEX" in example config
> Kill Tracker - Fix reported unit type

- AUTHORS.txt
- addons/field_rations/stringtable.xml
- addons/fortify/stringtable.xml
- addons/headless/stringtable.xml
- addons/intelitems/stringtable.xml
Added missing Russian translation and some fixes for readability.
> Translations - Russian

- addons/fortify/ACEX_Fortify_Presets.hpp
- addons/fortify/Cfg3DEN.hpp
- addons/fortify/CfgVehicles.hpp
- addons/fortify/config.cpp
- addons/fortify/functions/fnc_setupModule.sqf
- addons/fortify/stringtable.xml
- Make the fortify module check missionConfigFile and configFile, instead of being hardcoded.
> Fortify - Make module dynamically check config for presets

- .vscode/settings.json
- addons/field_rations/stringtable.xml
- addons/fortify/stringtable.xml
- addons/headless/stringtable.xml
- addons/intelitems/stringtable.xml
- addons/killtracker/stringtable.xml
- addons/viewrestriction/stringtable.xml
- addons/volume/stringtable.xml
Adding missing translations as part of ongoing issue: https://github.com/acemod/ACEX/issues/17
This change completes the Polish translation of ACEx adding in the remaining 58 entries
> Add missing Polish translations

- tools/stringtable_validator.py
Show bad line
```
Checking addons\volume\stringtable.xml:
ERROR: Failed to parse file. mismatched tag: line 75, column 10
```
> Improve stringtable validator

- addons/field_rations/stringtable.xml
Added missing Polish translation.
> Translations - Polish

- addons/field_rations/stringtable.xml
- addons/fortify/stringtable.xml
- addons/intelitems/stringtable.xml
- addons/killtracker/stringtable.xml
- addons/sitting/stringtable.xml
- addons/viewrestriction/stringtable.xml
- addons/volume/stringtable.xml
Added missing translation to Turkish
> Translations - Turkish
