addons/viewrestriction/XEH_clientInit.sqf, addons/viewrestriction/functions/fnc_canChangeCamera.sqf, addons/viewrestriction/functions/fnc_changeCamera.sqf, addons/viewrestriction/functions/fnc_selectiveChangeCamera.sqf
- Title - fix #27 
- Replace player events with CBA player events
- Improve performance with parameters
- Capitalize camera views to be same as `cameraView` returns
=> Fix gunner and group view being disallowed when using View Restriction

addons/headless/config.cpp, addons/headless/script_component.hpp, addons/main/config.cpp, addons/main/script_component.hpp, addons/main/script_mod.hpp, addons/sitting/config.cpp, addons/sitting/script_component.hpp, addons/viewrestriction/config.cpp, addons/viewrestriction/script_component.hpp
- Mirror https://github.com/acemod/ACE3/pull/3960
- Add "beautified" component names
- Add the component name macro
=> Add beautified component names

addons/killtracker/$PBOPREFIX$, addons/killtracker/CfgEventHandlers.hpp, addons/killtracker/README.md, addons/killtracker/XEH_postInit.sqf, addons/killtracker/config.cpp, addons/killtracker/script_component.hpp, addons/killtracker/stringtable.xml
Redo https://github.com/acemod/ACE3/pull/4229 as an addon for acex
Will show kills at mission end screen.
Attempts to ID killer when unit's death was scripted.
Example below, note the vanilla kill system only shows 2 kills where as this system shows 5.
The last damage source isn't going to be perfect; e.g. get shot once, and then fall out of a chopper 30 minutes later.
=> Add kill/death tracker to acex

addons/headless/ACE_Settings.hpp, addons/headless/CfgVehicles.hpp, addons/headless/XEH_PREP.hpp, addons/headless/XEH_preInit.sqf, addons/headless/functions/fnc_endMissionNoPlayers.sqf, addons/headless/functions/fnc_handleDisconnect.sqf, addons/headless/functions/fnc_handleInitPost.sqf, addons/headless/functions/fnc_moduleInit.sqf, addons/headless/stringtable.xml
- Close #24 
- Adds a setting to Headless module to end mission when no players are present anymore, this mimics `persistent = 0;` in server config, however that server config entry does not make the mission end if headless clients are present.
=> End mission on all players leaving when Headless Clients are present

addons/killtracker/XEH_postInit.sqf
We've been using this for about a month, kept getting reports of friendly fire that shouldn't.
I think the cause could be group switching on medical.
Easiest solution is to just use the `side` in the unit's config.
=> Fix erroneous firendly fire msg if side is weird

addons/sitting/functions/fnc_canSit.sqf
- Title
Player could chain sitting from one chair to the other, taking ownership of all of them so no one else including that player could sit on it again.
=> Prevent sitting on another chair if already sitting

addons/headless/functions/fnc_transferGroups.sqf
- Allow mission makers to blacklist a group, previously only units were checked
=> Allow headless blacklist on group, Fix empty group check

addons/sitting/CfgEventHandlers.hpp, addons/sitting/XEH_clientInit.sqf, addons/sitting/XEH_preInit.sqf
- Initialize sit actions only on clients with interface and if sitting is enabled
- Use CBA Class Event Handler for initialization, applied retroactively
- Remove `settingChanged` EH as it cannot be enabled mid-mission
=> Optimize Sitting initialization

addons/volume/XEH_postInitClient.sqf
- Fix this issue: https://github.com/acemod/ACEX/issues/77
Volume state isn't persisted, instead it's just restored. I don't think there's any need to over complicate it.
=> Fix volume state after respawn

addons/sitting/functions/fnc_sit.sqf
- Stand up if player is moved from seat position (e.g teleported)
The chairs I tested on the diff was < 0.2. 1m enough or too high?
=> (sitting) stand up if player moved

addons/sitting/functions/fnc_sit.sqf
fix #67
Thanks to shukari - https://github.com/acemod/ACEX/pull/84#issuecomment-346943680
on DC:
```
(getPosASL _seat) vectorDistance _seatPosOrig=1.43051e-006 
```
=> Sitting - Handle very small movements of seat

addons/headless/functions/fnc_moduleInit.sqf, addons/sitting/functions/fnc_moduleInit.sqf, addons/viewrestriction/functions/fnc_moduleInit.sqf
`ace_common_fnc_readSettingFromModule` now only has local effects, 
so modules must be read on all machines
=> CBA Settings Compat - Run readSettingFromModule on all machines

addons/headless/XEH_preInit.sqf, addons/headless/functions/fnc_handleSpawn.sqf, addons/headless/functions/fnc_transferGroups.sqf, addons/headless/script_component.hpp
- Improve #86 
- Set global variable only on server where it is used
- Set blacklist variable on object if object is in blacklist (by type, `isKindOf`), removes need to manually check during transfer, but only once on spawn
I'd like to improve `blacklistType` into proper API (CBA Settings maybe?), but this can be merged for 3.3.0 if someone can test it.
=> Improve Headless type blacklist

addons/sitting/functions/fnc_addSitActions.sqf
- Remove left-over from #59 
- Sitting initialization changed to `CBA_addClassEventHandler` so this isn't necessary anymore
=> Remove redundant run at settings init in Sitting

addons/fortify/XEH_postInit.sqf, addons/fortify/functions/fnc_canFortify.sqf
=> Fortify - Require tool to remove objects

addons/fortify/XEH_PREP.hpp, addons/fortify/XEH_preInit.sqf, addons/fortify/functions/fnc_addDeployHandler.sqf, addons/fortify/functions/fnc_deployObject.sqf
- Allow mission makers to register deployment handlers/validators so that they get more control of when a placement is possible. Inspired by ace explosives handlers.
- Adds a local event when deployment starts, e.g for displaying hints or possibilities of placement
Use case examples:
- Mission maker can control max height of placement
- Mission maker can check for nearby objects / disallow placing things too close
=> (fortify) allow custom deploy handlers

AUTHORS.txt, addons/killtracker/XEH_postInit.sqf
This keeps track of the player's kills in a new killCount variable, and prepends the mission debrief text with "Total Kills: <number>".
Thanks!
=> Killtracker: Add "Total Kills: <number>" to top of output.

addons/headless/CfgEventHandlers.hpp
- `preStart` EH was missing from CfgEventHandlers
=> Headless - Add preStart to CfgEventHandlers

addons/fortify/functions/fnc_addDeployHandler.sqf, addons/fortify/functions/fnc_deployObject.sqf
- Improve deploy handlers checking
- Add check for empty code block or useless code block `{true}` in `addDeployHandler` function
=> Fortify - Improve deploy handlers check

addons/headless/CfgVehicles.hpp, addons/sitting/CfgVehicles.hpp, addons/viewrestriction/CfgVehicles.hpp
- Setting modules should be hidden after converting to CBA settings
=> CBA Settings Compat - Hide setting modules

addons/viewrestriction/functions/fnc_canChangeCamera.sqf, addons/viewrestriction/functions/fnc_switchPreserveView.sqf
- title.
Some vehicles (e.g. CUP Challenger 2) have only `GUNNER` view instead of `INTERNAL`. In such vehicles View Preserving doesn't work.
=> View Restriction - Fix preserve view for vehicles with GUNNER view only

addons/headless/functions/fnc_endMissionNoPlayers.sqf, addons/headless/functions/fnc_handleConnectHC.sqf, addons/headless/functions/fnc_handleDisconnect.sqf, addons/headless/functions/fnc_handleSpawn.sqf, addons/headless/functions/fnc_rebalance.sqf, addons/headless/functions/fnc_transferGroups.sqf
- Title - fix #105 
- Reorganize code for readability in bugged function
- Cleanup headers (trailing `;`)
=> Headless - Fix end mission not respecting virtual curators

addons/field_rations/functions/fnc_getRemainingWater.sqf
- Change a `0` to `-1` to fix critical bug of water source actions on terrain objects that should not be sources
- Close #148
=> Field Rations - Fix terrain objects acting as water sources

addons/field_rations/CfgVehicles.hpp
- Config inherited the wrong class, close #150 
- Add action offsets for water pumps
=> Field Rations - Fix no model for water pumps and add action offset

addons/fortify/XEH_postInit.sqf, addons/fortify/functions/fnc_canFortify.sqf, addons/fortify/functions/fnc_setupModule.sqf
=> Fortify - Use uniqueItems common function

AUTHORS.txt, addons/field_rations/functions/fnc_consumeItem.sqf, addons/field_rations/functions/fnc_refillItem.sqf
Adds local CBA events when consuming items or refilling items.
Reason for this is, there is no way to interact with this so far on mission level. If someone wants to manipulate how much an item quenches thirst or how much hunger is sated it has to be done via mod right now.
This also means scripters can add their own logic when someone consumes a certain item or refills at a certain water source.
=> Field Rations - Add CBA events for consuming items and refiling bottles

addons/field_rations/XEH_postInit.sqf, addons/field_rations/initSettings.sqf, addons/field_rations/stringtable.xml
- Add `affectAdvancedFatigue` setting
- Change duty factor values to something more reasonable
- Based on observations after playing with system, old values drained stamina too quickly once thirst got high
- Goal is to have a noticeable effect when thirst is high without completely destroying stamina
- Capitalize setting names
=> Field Rations - Add setting to control effect on advanced fatigue

addons/headless/XEH_postInit.sqf, addons/headless/XEH_preInit.sqf, addons/headless/functions/fnc_transferGroups.sqf, addons/headless/initSettings.sqf, addons/headless/stringtable.xml
=> Add naked unit bug workaround

addons/main/script_mod.hpp
- Title
**Merge after https://github.com/CBATeam/CBA_A3/pull/1221 is released!**
=> Use CBA Versioning System properly

addons/intelitems/CfgVehicles.hpp
Don't think we need this
` Error Undefined variable in expression: object`
=> IntelItems - Remove condition from attributes

addons/killtracker/XEH_postInit.sqf
=> Kill Tracker - Support custom AI names

addons/field_rations/XEH_postInit.sqf, addons/field_rations/functions/fnc_handleHUD.sqf, addons/field_rations/functions/fnc_update.sqf
- Disable thirst and hunger for virtual units `VirtualMan_F`
- Hide HUD while a feature camera is active
- Close #182 , Close #187
=> Field Rations - Disable for virtual units, Hide HUD in feature cameras

addons/fortify/functions/fnc_addActions.sqf
=> Fortify - Display cost of item at start of interaction text

addons/field_rations/initSettings.sqf
- title, close currently active HUD whenever setting changes to force `handleHUD` function to create new HUD type
=> Field Rations - Fix changing HUD type while HUD is shown

addons/fortify/XEH_postInit.sqf
Hello,
Not sure at all if it is resolving this issue Fixes #209
Not tested!
- fortify remove action is added with a parent path `"ACE_MainActions"`
- Add `"ACE_MainActions"` in `ace_interact_menu_fnc_addActionToObject` (https://ace3mod.com/wiki/framework/interactionMenu-framework.html#33-fnc_addactiontoobject)
=> Fortify - Fix interaction overlapping remove object interaction

.github/workflows/documentation.yml
- Title
No need for any more permissions than this token provides as we are not pushing anything to the repository like in ACE3 (wiki updates).
=> Tools - Use `GITHUB_TOKEN` in documentation workflow

addons/main/script_mod.hpp
- Properly require ACE3 version 3.13.0 - was missed in 3.5.0.
=> General - Increase required ACE3 version

addons/field_rations/CfgVehicles.hpp, addons/field_rations/XEH_preStart.sqf
- Add missing interaction offset configs
- Close #174 
- Replace #213
=> Field Rations - Add missing interaction offsets

addons/intelitems/functions/fnc_addIntel.sqf
- `unitName addMagazine magazineName` -> needs local argument, but is executed on the server (https://community.bistudio.com/wiki/addMagazine)
- `[ACE_player, "acex_intelitems_notepad", "Notes!"] remoteExec ["acex_intelitems_fnc_addIntel", 2]` didnt work because of this on DS
- works on EditorMultiplayer because player == server == local argument
- fixes #203 please review @mharis001
=> Intel Items - Fix addIntel addMagazine locality

addons/field_rations/functions/fnc_drinkFromSource.sqf
- Title
We have a high thirst quenched modifier. Today a fireteam noticed that filling their canteens and drinking from those is way more efficient for some reason 😄
=> Make Thirst Quenched Coefficient Effect Water Sources

addons/field_rations/functions/fnc_handleEffects.sqf
=> Field Rations - Fix for changes to ace_medical

addons/fortify/functions/fnc_setupModule.sqf
```
Error in expression <ionConfigFile >> "ACEX_Fortify_Presets" >> _preset;
File z\acex\addons\fortify\functions\fnc_getPlaceableSet.sqf..., line 21
```
This breaks inside of a execNextFrame during CBA settings, and repeats forever
=> Fortify - Fix legacy module support
